# Configuration file for simulation
simulation:
  protocol: "BBM92"        # "BB84" or "BBM92"
  run_sim: True           # run simulation or not
  device: False           # use real device or not
  QPU: "ibm_sherbrooke"   # IBMQ device
  lengths: [15, 20, 30]   # list of chain lengths (distance between Alice and Bob) [15, 20, 30, 40, 50, 70, 100]
  runs: 300               # protocol runs per each length
  draw: False             # whether to draw or not